version: '2'

services:
  jenkins:
    image: docker.io/bitnami/jenkins:2
    user: root
    ports:
      - '80:8080'
    environment:
      - JENKINS_PASSWORD=bitnami
      - JENKINS_USERNAME=user
      - JENKINS_USER=root
      - TZ=America/Toronto
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
      - '/usr/bin/docker:/usr/bin/docker'
      - '/var/run/docker.sock:/var/run/docker.sock'

volumes:
  jenkins_data:
    driver: local

