{
 "title": "Pods Container Status",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   },
   { "name": "Container", "query": { "query": "label_values(container)" } },
   { "name": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(container_fs_reads_bytes_total{container=~\"$Container\",instance=\"$Node\"},device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod Status in default Namespace",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{pod=~\"^$Container.*\",namespace=~\"default\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "Pod Count For All Namespaces",
   "type": "graph",
   "gridPos": { "h": 4, "w": 11, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_info{namespace!=\"kube-system\"})",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Top 5 CPU Intense Pods ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5,sum(rate(container_cpu_system_seconds_total{pod!=\"\"}[5m])) by (pod) )",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top 5 Memory Intense Pod",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "GB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5,avg(container_memory_usage_bytes{image!=\"\"}) by (pod) /1024/1024/1024)"
    }
   ]
  },
  {
   "title": "Top 5 Network Intense Pods",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5,sum(rate(container_network_receive_bytes_total{pod!=\"\"}[5m])) by (pod))",
     "legendFormat": "Receive-{{pod}}"
    },
    {
     "expr": "topk(5,sum(rate(container_network_transmit_bytes_total{pod!=\"\"}[5m])) by (pod))",
     "legendFormat": "Transmit-{{pod}}"
    }
   ]
  },
  {
   "title": "Container Network Recieve Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_errors_total{container_name=~\"^$Container$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Container Network Transmit Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_network_transmit_errors_total{container_name=~\"^$Container$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pods network I/O ($interval avg)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 11, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (pod_name)",
     "legendFormat": "-> {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[$interval])) by (pod_name)",
     "legendFormat": "<- {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Disk IO Top 5 Pod Consumers",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(rate(container_fs_reads_total{pod!=\"\"}[5m])) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}