pipeline {
    agent any 
    environment{
        registryUrl = "https://ghcr.io/chance2021/devopsdaydayup"
        registryCredentialsId = '<dockerhub-credential-name>'        
        commitID = sh(script: 'git rev-parse --short HEAD', returnStdout:true).trim()
    }
    stages {
        stage('Build Image') { 
            steps {
                // 
                script {
                    dockerImage = docker.build registryUrl + ":$commitID"
                }
            }
        }
        stage('Test') { 
            steps {
                // 
                echo "This is Test"
            }
        }
        stage('Deploy') { 
            steps {
                // 
                echo "This is Deploy"
            }
        }
    }
}
