pipeline {
    agent any 
    environment{
        registryUrlBase = "https://ghcr.io"
        registryUrl = "ghcr.io/chance2021/devopsdaydayup"
        registryCredentialsId = 'github-token'
        commitID = sh(script: 'git rev-parse --short HEAD', returnStdout:true).trim()
    }
    stages {
        stage('Build and Push Image') { 
            steps {
                // 
                sh"whoami"
                script {
                    docker.withRegistry(registryUrlBase, registryCredentialsId) {
                        dockerImage = docker.build("$registryUrl:$commitID","./002-JenkinsCICD")
			dockerImage.push()
                    }
                }
            }
        }
        stage('Deploy') { 
            steps {
                // 
                echo "This is Deploy"
               // script {
               //     docker.withRegistry( '', registryCredential ) {
               //     dockerImage.push()
               // }
            }
        }
    }
}
